Repository jetstreamgg/tarmac, pull requests merged in 2025-06, with the labels that each got.

#317 fix rewards rate
  apps/webapp/src/modules/stake/components/StakeRewardsOverview.tsx
  packages/hooks/src/index.ts
  packages/widgets/src/widgets/BalancesWidget/components/StakeBalanceCard.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionDetail.tsx
Labels: ready for review

#313 Add Optimism and Unichain e2e tests and e2e testnets
  .github/workflows/e2e.yml
  apps/webapp/src/data/wagmi/config/config.e2e.ts
  apps/webapp/src/data/wagmi/config/testTenderlyChain.ts
  apps/webapp/src/test/e2e/fixtures.ts
  apps/webapp/src/test/e2e/tests/optimism-savings.spec.ts
  apps/webapp/src/test/e2e/tests/optimism-trade.spec.ts
  apps/webapp/src/test/e2e/tests/unichain-savings.spec.ts
  apps/webapp/src/test/e2e/tests/unichain-trade.spec.ts
  apps/webapp/src/test/e2e/utils/approveToken.ts
  apps/webapp/src/test/e2e/utils/constants.ts
  apps/webapp/src/test/e2e/utils/distributeRewards.ts
  apps/webapp/src/test/e2e/utils/getRpcUrlFromFile.ts
  apps/webapp/src/test/e2e/utils/newSealPosition.ts
  apps/webapp/src/test/e2e/utils/setBalance.ts
  apps/webapp/src/test/e2e/utils/updateSealDebtCeiling.ts
  packages/hooks/test/constants.ts
  packages/hooks/test/getRpcUrlFromFile.ts
  packages/hooks/test/tenderlyChain.ts
  packages/hooks/test/utils.ts
  packages/widgets/test/tenderlyChain.ts
  scripts/forkVnet.ts
Labels: ready for review

#315 Allow to sort stake delegates by alignment or total delegated
  .changeset/giant-buttons-agree.md
  packages/hooks/src/stake/useStakeUserDelegates.ts
  packages/widgets/src/widgets/StakeModuleWidget/components/SelectDelegate.tsx
Labels: ready for review

#321 Add new chains to combined history hooks
  packages/hooks/src/shared/useAllNetworksCombinedHistory.ts
  packages/utils/src/getExplorerName.ts
  packages/widgets/src/widgets/BalancesWidget/components/BalancesHeader.tsx
Labels: ready for review

#323 Fix popovers in interactiveStatsCards
  packages/widgets/src/shared/components/ui/PopoverRateInfo.tsx
  packages/widgets/src/shared/components/ui/card/InteractiveStatsCard.tsx
Labels: ready for review

#324 update useSubgraphUrl hook
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/modules/app/hooks/useSubgraphUrl.tsx
Labels: ready for review

#316 Add PSM tooltips
  apps/webapp/src/modules/app/hooks/useNotification.tsx
  apps/webapp/src/modules/layout/components/ConnectCard.tsx
  apps/webapp/src/modules/rewards/components/RewardsTokenInfo.tsx
  apps/webapp/src/modules/savings/components/SavingsRateCard.tsx
  apps/webapp/src/modules/savings/getSavingsFaqItems.ts
  apps/webapp/src/modules/stake/components/StakeOverview.tsx
  apps/webapp/src/modules/stake/components/StakeRewardsOverview.tsx
  apps/webapp/src/modules/trade/getTradeFaqItems.ts
  apps/webapp/src/modules/ui/components/FaqAccordion.tsx
  apps/webapp/src/modules/ui/components/HighlightRate.tsx
  apps/webapp/src/modules/ui/components/PopoverInfo.tsx
  packages/utils/src/getChainSpecificText.ts
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/widgets/L2TradeWidget/index.tsx
  packages/widgets/src/widgets/TradeWidget/index.tsx
Labels: ready for review

#325 Add rate to staking rewards reward selection
  apps/webapp/src/modules/stake/components/StakeRewardsOverview.tsx
  packages/hooks/src/stake/useStakeRewardsData.ts
  packages/widgets/src/widgets/StakeModuleWidget/components/SaRewardsCard.tsx
Labels: ready for review

#326 Fix accrued staking rewards balance
  apps/webapp/src/modules/stake/components/StakePositionOverview.tsx
  apps/webapp/src/modules/stake/components/StakePositionRewardsCard.tsx
Labels: ready for review

#334 fix decimal issue in stable <> stable swaps on PSM
  packages/widgets/src/widgets/L2TradeWidget/index.tsx
Labels: ready for review

#329 Add OP and Unichain to scarlett as valid chains
  apps/webapp/src/modules/chat/lib/intentUtils.ts
Labels: ready for review

#339 Handle trade for USDS notifications
  apps/webapp/src/modules/app/hooks/useNotification.tsx
  apps/webapp/src/modules/app/hooks/usePrepareNotification.tsx
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: ready for review

#336 remove error message on hover on token input when entering numbers with decimals
  packages/widgets/src/shared/components/ui/token/TokenInput.tsx
Labels: ready for review

#344 remove skyL2 token
  .github/workflows/e2e.yml
  packages/hooks/src/contracts.ts
  packages/hooks/src/generated.ts
  packages/hooks/src/index.ts
  packages/hooks/src/tokens/tokens.constants.ts
  packages/widgets/src/config/default-config.ts
Labels: ready for review

#346 don't show loading skeletons in seal widget if not loading
  packages/widgets/src/widgets/SealModuleWidget/components/PositionSummary.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
Labels: ready for review

#349 try to use multiple chains
  .github/workflows/e2e.yml
  apps/webapp/src/test/e2e/fixtures.ts
  scripts/forkVnet.ts
Labels: WIP

#348 Fix issue causing duplicate rerender cycles in the L2 trade widget
  packages/widgets/src/widgets/L2TradeWidget/components/L2TradeInputs.tsx
  packages/widgets/src/widgets/L2TradeWidget/index.tsx
Labels: ready for review

#355 Update PSM tooltip and ConnectCard copy
  apps/webapp/src/modules/layout/components/ConnectCard.tsx
  apps/webapp/src/modules/stake/getStakeFaqItems.ts
  apps/webapp/src/modules/ui/components/PopoverInfo.tsx
  apps/webapp/src/modules/upgrade/getUpgradeFaqItems.ts
  packages/utils/src/getChainSpecificText.ts
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: ready for review

#357 Add ChainModal context and refactor ChainModal component
  apps/webapp/src/modules/ui/components/ChainModal.tsx
  apps/webapp/src/modules/ui/context/ChainModalContext.tsx
  apps/webapp/src/pages/App.tsx
Labels: ready for review

#361 show stakingBalanceCard if balance is 0
  packages/widgets/src/widgets/BalancesWidget/components/StakeBalanceCard.tsx
Labels: ready for review

#363 fix stake card address
  apps/webapp/src/modules/ui/components/AboutStakeModule.tsx
  packages/hooks/src/index.ts
Labels: ready for review

#370 Add action for sky token in the balances widget
  apps/webapp/src/modules/app/hooks/useActionForToken.tsx
  apps/webapp/src/public/tokens/actions/sky.png
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: ready for review

#377 Update latest faqs
  apps/webapp/src/modules/stake/getStakeFaqItems.ts
  apps/webapp/src/modules/ui/constants/sharedFaqItems.ts
  apps/webapp/src/modules/upgrade/getUpgradeFaqItems.ts
Labels: ready for review

#376 Fix duplicated stake widget issue
  .changeset/red-masks-train.md
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
Labels: ready for review

#381 Add script to generate PR description
  README.md
  package.json
  scripts/generate_pr_description.sh
Labels: ready for review

#383 add missing lines to faqs
  apps/webapp/src/modules/savings/getSavingsFaqItems.ts
  apps/webapp/src/modules/trade/getTradeFaqItems.ts
Labels: ready for review

#388 dev -> staging
  .changeset/red-masks-train.md
  README.md
  apps/webapp/src/data/wagmi/config/config.default.ts
  apps/webapp/src/modules/savings/getSavingsFaqItems.ts
  apps/webapp/src/modules/trade/getTradeFaqItems.ts
  package.json
  packages/utils/src/locales/en.po
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es.po
  packages/utils/src/locales/ko.po
  packages/widgets/CHANGELOG.md
  packages/widgets/package.json
  packages/widgets/src/widgets/TradeWidget/lib/constants.ts
  scripts/generate_pr_description.sh
Labels: ready for review, release PR

#398 Stake help modal qa
  apps/webapp/src/modules/stake/components/StakeHelpModal.tsx
  apps/webapp/src/modules/ui/components/PopoverInfo.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
Labels: ready for review

#399 development -> staging
  apps/webapp/.env.example
  apps/webapp/README.md
  apps/webapp/src/modules/chat/hooks/useSendMessage.tsx
  apps/webapp/src/modules/stake/components/StakeHelpModal.tsx
  apps/webapp/src/modules/ui/components/PopoverInfo.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
Labels: ready for review

#397 Add additional ignore patterns in PR description script
  scripts/generate_pr_description.sh
Labels: ready for review

#374 Add SPK
  apps/webapp/src/modules/rewards/components/RewardsDetailsView.tsx
  apps/webapp/src/modules/rewards/components/RewardsFaq.tsx
  apps/webapp/src/modules/rewards/components/RewardsTokenInfo.tsx
  apps/webapp/src/modules/rewards/hooks/useRewardsSuppliersCount.tsx
  apps/webapp/src/modules/rewards/lib/getRewardsSpkFaqItems.ts
  apps/webapp/src/modules/stake/components/StakeRewardsOverview.tsx
  apps/webapp/src/modules/ui/components/AboutSpk.tsx
  apps/webapp/src/modules/ui/components/ActionsShowcase.tsx
  apps/webapp/src/modules/ui/components/HighlightRate.tsx
  apps/webapp/src/modules/ui/components/LinkedActionCard.tsx
  apps/webapp/src/modules/ui/hooks/useUserSuggestedActions.ts
  apps/webapp/src/public/tokens/base/spk.svg
  apps/webapp/src/public/tokens/ethereum/spk.svg
  apps/webapp/src/public/tokens/spk.png
  apps/webapp/src/public/tokens/spk.svg
  packages/hooks/src/contracts.ts
  packages/hooks/src/generated.ts
  packages/hooks/src/index.ts
  packages/hooks/src/rewards/useAvailableTokenRewardContracts.ts
  packages/hooks/src/tokens/tokens.constants.ts
  packages/widgets/src/config/default-config.ts
  packages/widgets/src/widgets/BalancesWidget/components/BalancesContent.tsx
  packages/widgets/src/widgets/BalancesWidget/components/ModulesBalances.tsx
  packages/widgets/src/widgets/BalancesWidget/components/RewardsBalanceCard.tsx
  packages/widgets/src/widgets/RewardsWidget/components/RewardsStatsCard.tsx
Labels: WIP, feature

#463 Gp/balances highest rate
  packages/hooks/src/index.ts
  packages/hooks/src/seal/useClaimRewards.ts
  packages/hooks/src/seal/useDrawUsds.ts
  packages/hooks/src/seal/useWipe.ts
  packages/hooks/src/seal/useWipeAll.ts
  packages/hooks/src/stake/useClaimRewards.ts
  packages/hooks/src/stake/useDrawUsds.ts
  packages/hooks/src/stake/useHighestRateFromChartData.ts
  packages/hooks/src/stake/useWipe.ts
  packages/hooks/src/stake/useWipeAll.ts
  packages/widgets/src/widgets/BalancesWidget/components/RewardsBalanceCard.tsx
  packages/widgets/src/widgets/BalancesWidget/components/StakeBalanceCard.tsx
Labels: ready for review

#390 use the prod BA labs endpoint when connected to tenderly
  packages/hooks/src/helpers/getSubgraphUrl.ts
Labels: ready for review

#441 Batch toggle disabling functionality and read feature flag for initial state of `batchEnabled`
  apps/webapp/src/components/BatchTransactionsToggle.tsx
  apps/webapp/src/modules/config/context/ConfigContext.tsx
Labels: ready for review
