Repository jetstreamgg/tarmac, pull requests merged in 2025-04, with the labels that each got.

#196 Change Migrate back to Upgrade
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/app/hooks/useActionForToken.tsx
  apps/webapp/src/modules/balances/components/BalancesModuleShowcase.tsx
  apps/webapp/src/modules/ui/hooks/useUserSuggestedActions.ts
  apps/webapp/src/modules/upgrade/components/UpgradeDetails.tsx
  apps/webapp/src/modules/upgrade/components/UpgradedDaiToUsds.tsx
  apps/webapp/src/modules/upgrade/components/UpgradedMkrToSky.tsx
  apps/webapp/src/test/e2e/tests/la-u-r.spec.ts
  apps/webapp/src/test/e2e/tests/la-u-s.spec.ts
  apps/webapp/src/test/e2e/tests/upgrade.spec.ts
  apps/webapp/src/test/e2e/utils/approveOrPerformAction.ts
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/widgets/BalancesWidget/lib/getTitle.ts
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeStats.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeTransactionStatus.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
  packages/widgets/src/widgets/UpgradeWidget/lib/constants.ts
  packages/widgets/src/widgets/UpgradeWidget/tests/upgradeWidget.test.tsx
Labels: ready for review

#198 New Stake copy
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/icons/Stake.tsx
  apps/webapp/src/modules/icons/index.ts
  apps/webapp/src/modules/stake/components/StakeHistory.tsx
  apps/webapp/src/modules/stake/components/StakeOverview.tsx
  apps/webapp/src/modules/stake/components/StakePositionDetails.tsx
  apps/webapp/src/modules/ui/components/AboutStakeModule.tsx
  apps/webapp/src/test/e2e/tests/stake.spec.ts
  apps/webapp/src/test/e2e/utils/approveOrPerformAction.ts
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/widgets/StakeModuleWidget/components/Borrow.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Free.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Lock.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/OpenNewUrn.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionDetail.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionDetailsAccordion.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionSummary.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Repay.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/StakeModuleTransactionStatus.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/UnconnectedState.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
  packages/widgets/src/widgets/StakeModuleWidget/lib/constants.ts
Labels: ready for review

#194 Update EthFlow contract address in Mainnet
  .changeset/two-colts-fold.md
  packages/hooks/src/contracts.ts
  packages/hooks/src/generated.ts
  packages/hooks/src/index.ts
  packages/hooks/wagmi.config.ts
Labels: ready for review

#199 Update Stake icon
  apps/webapp/src/modules/icons/Stake.tsx
Labels: ready for review

#203 Filter not allowed actions
  apps/webapp/src/lib/utils.ts
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/chat/hooks/useSendMessage.tsx
  apps/webapp/src/modules/chat/lib/confirmationWarningMetadata.ts
  apps/webapp/src/modules/chat/lib/intentUtils.ts
Labels: ready for review

#200 Show soon label in the Rewards tab for L2s
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/modules/balances/components/BalancesModuleShowcase.tsx
Labels: ready for review

#205 Add hooks to retrieve seal migrations
  packages/hooks/src/index.ts
  packages/hooks/src/seal/checkUrnMigrationStatus.ts
  packages/hooks/src/seal/sealModule.d.ts
  packages/hooks/src/seal/useIsUrnMigrated.ts
  packages/hooks/src/seal/useSealMigrations.ts
  packages/widgets/src/widgets/SealModuleWidget/components/UrnsList.tsx
Labels: ready for review

#206 Handle Query params and external state in the Stake widget
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/modules/stake/components/StakeWidgetPane.tsx
  packages/widgets/src/shared/components/ui/token/TokenInput.tsx
  packages/widgets/src/shared/types/widgetState.d.ts
  packages/widgets/src/widgets/StakeModuleWidget/components/Free.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Lock.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/OpenNewUrn.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/UnconnectedState.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
Labels: ready for review

#209 Update Seal Engine deprecation messages
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/widgets/SealModuleWidget/components/UrnsList.tsx
Labels: ready for review

#210 Add a connect wallet screen to the Seal migration page
  apps/webapp/src/modules/app/components/SealMigrationWidgetPane.tsx
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: ready for review

#211 Don't allow to manage seal position without collateral
  packages/widgets/src/widgets/SealModuleWidget/components/UrnPosition.tsx
Labels: ready for review

#212 Enable multi injected provider discovery
  apps/integration-ui/src/modules/providers/wagmi.ts
  apps/webapp/src/data/wagmi/config/config.default.ts
Labels: ready for review

#216 Update chatbot endpoint
  apps/webapp/src/modules/chat/hooks/useSendMessage.tsx
Labels: ready for review

#215 Update Seal details pane
  apps/webapp/src/modules/seal/components/SealOverview.tsx
  apps/webapp/src/modules/seal/components/SealPositionDetails.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/PositionDetail.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/UrnPosition.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/UrnsList.tsx
  packages/widgets/src/widgets/SealModuleWidget/context/context.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
  packages/widgets/src/widgets/SealModuleWidget/lib/types.ts
Labels: ready for review

#223 Updates in migration widget
  apps/webapp/src/modules/app/components/SealMigrationWidgetPane.tsx
  packages/widgets/src/widgets/BalancesWidget/components/SealBalanceCard.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/PositionDetail.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/SealModuleTransactionStatus.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/UrnPosition.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/UrnsList.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
  packages/widgets/src/widgets/SealModuleWidget/lib/constants.ts
Labels: do not merge

#224 Add MKR SKY to trade disallowed pairs config
  packages/widgets/src/config/default-config.ts
Labels: ready for review, do not merge

#222 Fetch next valid stake urn index for migration
  packages/hooks/src/index.ts
  packages/hooks/src/seal/nextMigrationUrnIndex.test.tsx
  packages/hooks/src/seal/useNextMigrationUrnIndex.ts
  packages/widgets/src/widgets/SealModuleWidget/components/MigrateAbout.tsx
Labels: ready for review, do not merge

#220 Update testnet name
  apps/webapp/src/data/wagmi/config/config.default.ts
Labels: ready for review

#214 Add log error when execute is called with no simulation data
  .changeset/fresh-eyes-dress.md
  packages/hooks/src/shared/useWriteContractFlow.ts
Labels: RFC

#227 Wire up stake module
  apps/webapp/vite.config.ts
  packages/hooks/src/index.ts
  packages/hooks/src/stake/useClaimRewards.ts
  packages/hooks/src/stake/useDrawUsds.ts
  packages/hooks/src/stake/useFreeCollateral.ts
  packages/hooks/src/stake/useLockCollateral.ts
  packages/hooks/src/stake/useOpenUrn.ts
  packages/hooks/src/stake/usePositionsAtRisk.ts
  packages/hooks/src/stake/useSelectStakeRewardContract.ts
  packages/hooks/src/stake/useSelectStakeVoteDelegate.ts
  packages/hooks/src/stake/useStakeAllowance.ts
  packages/hooks/src/stake/useStakeApprove.ts
  packages/hooks/src/stake/useStakeExitFee.ts
  packages/hooks/src/stake/useStakeMulticall.ts
  packages/hooks/src/stake/useStakeRewardContracts.ts
  packages/hooks/src/stake/useUrnSelectedRewardContract.ts
  packages/hooks/src/stake/useUrnSelectedVoteDelegate.ts
  packages/hooks/src/stake/useWipe.ts
  packages/hooks/src/stake/useWipeAll.ts
  packages/widgets/src/widgets/StakeModuleWidget/components/Borrow.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/DelegateCard.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Free.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionDetail.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionSummary.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Repay.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/SaRewardsCard.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/SelectDelegate.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/SelectRewardContract.tsx
  packages/widgets/src/widgets/StakeModuleWidget/context/context.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
Labels: ready for review

#229 New About step in the Seal migration flow
  apps/webapp/src/public/images/banner_migration.png
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/widgets/SealModuleWidget/components/LineItem.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/MigrateAbout.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/MigratePositionSummary.tsx
  packages/widgets/src/widgets/SealModuleWidget/context/context.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
Labels: ready for review

#230 Bump the all-dependencies group across 1 directory with 61 updates
  apps/integration-ui/package.json
  apps/webapp/package.json
  package.json
  packages/hooks/package.json
  packages/utils/package.json
  packages/widgets/package.json
  pnpm-lock.yaml
Labels: dependencies, ready for review

#225 various updates to widget UI navigation
  apps/webapp/src/public/images/banner_migration.png
  packages/hooks/src/seal/useNextMigrationUrnIndex.ts
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/widgets/SealModuleWidget/components/LineItem.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/MigrateAbout.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/MigratePositionSummary.tsx
  packages/widgets/src/widgets/SealModuleWidget/context/context.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
  packages/widgets/src/widgets/SealModuleWidget/lib/constants.ts
  packages/widgets/src/widgets/SealModuleWidget/lib/utils.ts
  packages/widgets/src/widgets/StakeModuleWidget/components/StakeModuleTransactionStatus.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/UrnPosition.tsx
Labels: ready for review

#232 Show selected reward and delegate in the Stake flow
  packages/widgets/src/widgets/SealModuleWidget/components/PositionDetail.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/UrnPosition.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/UrnPosition.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
Labels: ready for review
