Repository jetstreamgg/tarmac, pull requests merged in 2025-07, with the labels that each got.

#470 Stake claim token fix
  apps/webapp/src/modules/rewards/components/RewardsTokenInfo.tsx
  apps/webapp/src/modules/stake/components/StakeHistory.tsx
  apps/webapp/src/modules/ui/components/HighlightRate.tsx
Labels: ready for review, hotfix

#474 main -> development
  apps/webapp/src/modules/rewards/components/RewardsTokenInfo.tsx
  apps/webapp/src/modules/stake/components/StakeHistory.tsx
  apps/webapp/src/modules/stake/components/StakeRewardsOverview.tsx
  apps/webapp/src/modules/ui/components/HighlightRate.tsx
  packages/hooks/src/index.ts
  packages/hooks/src/seal/useClaimRewards.ts
  packages/hooks/src/seal/useDrawUsds.ts
  packages/hooks/src/seal/useWipe.ts
  packages/hooks/src/seal/useWipeAll.ts
  packages/hooks/src/stake/useClaimRewards.ts
  packages/hooks/src/stake/useDrawUsds.ts
  packages/hooks/src/stake/useHighestRateFromChartData.ts
  packages/hooks/src/stake/useWipe.ts
  packages/hooks/src/stake/useWipeAll.ts
  packages/widgets/src/widgets/BalancesWidget/components/RewardsBalanceCard.tsx
  packages/widgets/src/widgets/BalancesWidget/components/StakeBalanceCard.tsx
Labels: ready for review

#477 Prevent TokenInput overflow by limiting integer digits
  packages/widgets/src/shared/components/ui/token/TokenInput.tsx
Labels: ready for review

#490 Widget overview datapoints
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/shared/components/ui/transaction/TransactionOverview.tsx
  packages/widgets/src/widgets/L2SavingsWidget/components/L2SavingsSupplyWithdraw.tsx
  packages/widgets/src/widgets/L2TradeWidget/index.tsx
  packages/widgets/src/widgets/RewardsWidget/index.tsx
  packages/widgets/src/widgets/SavingsWidget/components/SupplyWithdraw.tsx
  packages/widgets/src/widgets/TradeWidget/components/TradeDetails.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeRevert.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#492 add lingui packages to a group for dependabot
  .github/dependabot.yml
Labels: ready for review

#468 Refactor useTokenBalances hook to avoid calling wagmi hooks in a loop
  apps/webapp/src/data/wagmi/config/config.default.ts
  apps/webapp/src/data/wagmi/config/testTenderlyChain.ts
  packages/hooks/src/tokens/useTokenBalance.ts
Labels: ready for review

#517 Preprod -> Main
  .changeset/fine-groups-laugh.md
  packages/hooks/README.md
  packages/hooks/generate-with-retry.js
  packages/hooks/package.json
  packages/hooks/src/contracts.ts
  packages/hooks/src/generated.ts
  packages/hooks/src/index.ts
  packages/hooks/src/upgrade/useSkyToMkr.ts
  packages/hooks/src/upgrade/useUpgradeHistory.ts
  packages/widgets/src/widgets/UpgradeWidget/hooks/useUpgraderManager.tsx
Labels: ready for review

#526 always default to dai / usds when toggling tabs in upgrade widget
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#543 Bundled transactions copy
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/shared/components/ui/transaction/TransactionOverview.tsx
  packages/widgets/src/shared/components/ui/transaction/TransactionReview.tsx
  packages/widgets/src/widgets/L2TradeWidget/lib/constants.ts
  packages/widgets/src/widgets/RewardsWidget/lib/constants.ts
  packages/widgets/src/widgets/SavingsWidget/lib/constants.ts
  packages/widgets/src/widgets/StakeModuleWidget/lib/constants.ts
  packages/widgets/src/widgets/TradeWidget/lib/constants.ts
  packages/widgets/src/widgets/UpgradeWidget/lib/constants.ts
Labels: ready for review

#438 Add vertical tab menu
  apps/webapp/src/components/ui/sheet.tsx
  apps/webapp/src/modules/app/components/AppContainer.tsx
  apps/webapp/src/modules/app/components/SealMigrationWidgetPane.tsx
  apps/webapp/src/modules/app/components/WidgetNavigation.tsx
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/app/types/Widgets.d.ts
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: ready for review

#561 Refactor token list configuration, add SPK to restricted lists
  apps/webapp/src/modules/config/default-config.ts
  apps/webapp/src/modules/config/tokenListConfig.ts
  packages/widgets/src/config/default-config.ts
Labels: ready for review

#570 Fix re-render when interacting with notifications
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/modules/app/hooks/useBatchTxNotification.tsx
  apps/webapp/src/modules/app/hooks/useChatNotification.tsx
  apps/webapp/src/modules/app/hooks/useDismissChatSuggestion.tsx
  apps/webapp/src/modules/app/hooks/useGovernanceMigrationToast.tsx
  apps/webapp/src/modules/app/hooks/usePageLoadNotifications.tsx
  apps/webapp/src/modules/config/context/ConfigContext.tsx
  apps/webapp/src/modules/config/types/user-config.ts
Labels: ready for review

#577 Implement step indicator visibility in Rewards widget based on flow
  packages/widgets/src/widgets/RewardsWidget/index.tsx
Labels: ready for review

#578 get spk trades showing in tx history
  packages/hooks/src/tokens/tokens.constants.ts
Labels: ready for review

#580 Extend nav drawer menu to tablet layout and other widget navigation udpdates
  apps/webapp/src/components/DualSwitcher.tsx
  apps/webapp/src/modules/app/components/AppContainer.tsx
  apps/webapp/src/modules/app/components/WidgetNavigation.tsx
  apps/webapp/src/modules/app/components/WidgetPane.tsx
Labels: ready for review

#586 new testnet -> development
  apps/webapp/src/data/wagmi/config/config.default.ts
  apps/webapp/src/data/wagmi/config/testTenderlyChain.ts
  apps/webapp/src/modules/stake/components/StakeOverview.tsx
  apps/webapp/src/modules/stake/components/StakePositionOverview.tsx
  apps/webapp/src/test/e2e/tests/stake.spec.ts
  apps/webapp/src/test/e2e/utils/constants.ts
  apps/webapp/src/test/e2e/utils/distributeRewards.ts
  apps/webapp/src/test/e2e/utils/testWallets.ts
  apps/webapp/src/test/e2e/utils/updateSealDebtCeiling.ts
  package.json
  packages/hooks/src/contracts.ts
  packages/hooks/src/generated.ts
  packages/hooks/src/prices/useLsMkrPrice.ts
  packages/hooks/src/psm/supplyAndWithdrawSavingsBase.test.tsx
  packages/hooks/src/rewards/supplyAndWithdrawRewards.test.tsx
  packages/hooks/src/savings/supplyAndWithdrawSavings.test.tsx
  packages/hooks/src/savings/useSavingsData.test.tsx
  packages/hooks/src/savings/useSavingsSupply.ts
  packages/hooks/src/savings/useSavingsWithdraw.ts
  packages/hooks/src/seal/usePositionsAtRisk.ts
  packages/hooks/src/stake/openLockFreeSky.test.tsx
  packages/hooks/src/stake/saMulticall.test.tsx
  packages/hooks/src/stake/usePositionsAtRisk.ts
  packages/hooks/src/vaults/calculateCollateralRiskParams.ts
  packages/hooks/src/vaults/helpers.ts
  packages/hooks/src/vaults/useCollateralData.ts
  packages/hooks/src/vaults/useSimulatedVault.test.tsx
  packages/hooks/src/vaults/useSimulatedVault.ts
  packages/hooks/src/vaults/useVault.ts
  packages/hooks/src/vaults/vaults.constants.ts
  packages/hooks/test/constants.ts
  packages/widgets/src/widgets/SealModuleWidget/components/Borrow.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Free.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/PositionSummary.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Repay.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Borrow.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/DelegateCard.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Free.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/OpenNewUrn.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionDetailsAccordion.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionSummary.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/Repay.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/UrnPosition.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
  scripts/forkVnet.ts
Labels: ready for review

#589 QA items
  packages/utils/src/formatValue.ts
  packages/widgets/src/shared/components/ui/PopoverRateInfo.tsx
  packages/widgets/src/shared/components/ui/token/TokenInput.tsx
Labels: ready for review

#581 Implement chatbot terms acceptance flow with new components and hooks
  apps/webapp/src/modules/app/components/MainApp.tsx
  apps/webapp/src/modules/chat/components/ChatBubble.tsx
  apps/webapp/src/modules/chat/components/ChatInput.tsx
  apps/webapp/src/modules/chat/components/ChatWithTerms.tsx
  apps/webapp/src/modules/chat/components/ChatbotTermsModal.tsx
  apps/webapp/src/modules/chat/constants.ts
  apps/webapp/src/modules/chat/context/ChatContext.tsx
  apps/webapp/src/modules/chat/hooks/useSendMessage.tsx
  apps/webapp/src/modules/chat/hooks/useTermsAcceptance.tsx
  apps/webapp/src/modules/chat/services/termsApi.ts
  apps/webapp/src/modules/chat/types/Chat.ts
  apps/webapp/src/modules/ui/components/TermsDialog.tsx
  apps/webapp/src/modules/ui/components/TermsModal.tsx
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: ready for review

#594 Add module subheaders
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/shared/components/ui/widget/WidgetContainer.tsx
  packages/widgets/src/widgets/BalancesWidget/index.tsx
  packages/widgets/src/widgets/L2SavingsWidget/index.tsx
  packages/widgets/src/widgets/L2TradeWidget/index.tsx
  packages/widgets/src/widgets/RewardsWidget/index.tsx
  packages/widgets/src/widgets/SavingsWidget/index.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
  packages/widgets/src/widgets/TradeWidget/components/TradeHeader.tsx
  packages/widgets/src/widgets/TradeWidget/index.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#596 Add new Tenderly RPC domain names to CSP
  apps/webapp/src/test/e2e/tests/reward-2.spec.ts
  apps/webapp/src/test/e2e/tests/upgrade.spec.ts
  apps/webapp/vite.config.ts
Labels: ready for review

#605 fix tests
  apps/webapp/playwright.config.ts
  apps/webapp/src/test/e2e/tests/upgrade.spec.ts
  package.json
  packages/hooks/test/helpers.ts
Labels: ready for review

#601 Add tooltip descriptions on widget menu items
  apps/webapp/src/modules/app/components/WidgetNavigation.tsx
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: ready for review

#607 Update graphql-request, date-fns and override @babel/runtime
  apps/webapp/package.json
  package.json
  packages/hooks/package.json
  packages/utils/package.json
  packages/utils/src/formatDate.ts
  packages/utils/src/locale.constants.ts
  pnpm-lock.yaml
Labels: ready for review

#608 add bridge links for optimism and unichain
  packages/widgets/src/widgets/BalancesWidget/components/BalancesHeader.tsx
Labels: ready for review

#610 Format SavingsSuppliersCard number
  apps/webapp/src/modules/savings/components/SavingsSuppliersCard.tsx
Labels: ready for review

#611 Dev > Staging
  apps/webapp/src/modules/app/components/WidgetNavigation.tsx
  apps/webapp/src/modules/savings/components/SavingsSuppliersCard.tsx
Labels: ready for review

#595 Ignore locale files and generate them on build
  .gitignore
  package.json
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: WIP

#628 dev -> staging
  .github/dependabot.yml
  .gitignore
  apps/webapp/src/modules/app/components/MainApp.tsx
  apps/webapp/src/modules/app/hooks/useBatchTxNotification.tsx
  apps/webapp/src/modules/app/hooks/useChatNotification.tsx
  apps/webapp/src/modules/app/hooks/useGovernanceMigrationToast.tsx
  apps/webapp/src/modules/app/hooks/usePageLoadNotifications.tsx
  package.json
  packages/utils/src/hooks/useIsMetaMaskWallet.ts
  packages/utils/src/index.ts
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/shared/components/ui/transaction/TransactionReview.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeTransactionReview.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#630 Fix connect card showing when connected
  apps/webapp/src/modules/balances/components/BalancesDetails.tsx
Labels: ready for review

#629 handle stusds balance module filtering
  packages/hooks/src/stusds/useStUsdsData.ts
  packages/hooks/src/tokens/tokens.constants.ts
  packages/widgets/src/config/default-config.ts
  packages/widgets/src/widgets/BalancesWidget/components/BalancesContent.tsx
Labels: ready for review

#635 Show the right network icons for the chatbot suggested actions
  apps/webapp/src/modules/chat/components/ChatIntentsRow.tsx
  apps/webapp/src/modules/chat/hooks/useNetworkFromUrl.tsx
  apps/webapp/src/modules/chat/lib/intentUtils.ts
Labels: ready for review
