Repository jetstreamgg/tarmac, pull requests merged in 2025-10, with the labels that each got.

#851 Add additional "About" cards on trade detail pane
  apps/webapp/src/modules/trade/components/AboutTokensCarousel.tsx
  apps/webapp/src/modules/trade/components/TradeDetails.tsx
  apps/webapp/src/modules/ui/components/AboutSUsds.tsx
  apps/webapp/src/modules/ui/components/AboutSky.tsx
  apps/webapp/src/modules/ui/components/AboutSpk.tsx
  apps/webapp/src/modules/ui/components/AboutStUsds.tsx
  apps/webapp/src/modules/ui/components/AboutUsds.tsx
  apps/webapp/src/modules/ui/components/GradientShapeCard.tsx
  apps/webapp/src/modules/ui/components/TokenIcon.tsx
Labels: ready for review

#883 stUSDS QA fixes
  apps/webapp/src/modules/expert/components/ExpertWidgetPane.tsx
  apps/webapp/src/modules/ui/components/LinkedActionCard.tsx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: WIP

#867 Remove expert modules feature flag
  apps/webapp/src/lib/feature-flags.ts
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/balances/components/BalancesModuleShowcase.tsx
  apps/webapp/src/modules/config/default-config.ts
  apps/webapp/src/modules/layout/components/ConnectCard.tsx
  apps/webapp/src/modules/ui/hooks/useUserSuggestedActions.ts
  apps/webapp/src/modules/utils/validateSearchParams.ts
  apps/webapp/src/test/e2e/tests/expert-stusds.spec.ts
Labels: ready for review

#847 Fix padding alignment issues across the widgets
  apps/webapp/src/components/DualSwitcher.tsx
  apps/webapp/src/modules/app/components/WidgetNavigation.tsx
  apps/webapp/src/modules/ui/components/ActionsShowcase.tsx
  apps/webapp/src/modules/ui/components/ArrowStepIndicator.tsx
  apps/webapp/src/modules/ui/components/LinkedActionWrapper.tsx
  packages/widgets/src/shared/components/ui/widget/WidgetContainer.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
Labels: ready for review

#885 Update token symbols for savings and stUSDS cards
  packages/widgets/src/widgets/BalancesWidget/components/SavingsBalanceCard.tsx
  packages/widgets/src/widgets/BalancesWidget/components/StUSDSBalanceCard.tsx
Labels: ready for review

#887 detail card layouts
  apps/webapp/src/modules/layout/components/ConnectCard.tsx
  apps/webapp/src/modules/ui/components/AboutCard.tsx
  apps/webapp/src/modules/ui/components/GradientShapeCard.tsx
Labels: ready for review

#889 Add stusds balance to widget
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSStatsCard.tsx
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSSupplyWithdraw.tsx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: ready for review

#891 Don't disable widget button after withdraw all
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSStatsCard.tsx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: ready for review

#890 Use liquidity tooltips when the user supply and withdraw amounts are limited
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSSupplyWithdraw.tsx
Labels: ready for review

#893 update stusds card gradient color
  apps/webapp/src/modules/ui/components/AboutStUsds.tsx
Labels: ready for review

#881 Add responsive container query styling for compact chat pane layout
  apps/webapp/src/modules/chat/components/ChatIntentsRow.tsx
  apps/webapp/src/modules/chat/components/ConfirmationWarningRow.tsx
  apps/webapp/src/modules/ui/components/markdown/ChatMarkdownRenderer.tsx
Labels: ready for review, chat

#896 Update savings card title to match the other cards
  packages/widgets/src/shared/components/ui/card/InteractiveStatsCardWithAccordion.tsx
  packages/widgets/src/widgets/BalancesWidget/components/SavingsBalanceCard.tsx
Labels: ready for review

#895 development -> staging
  apps/webapp/src/data/banners/banners.ts
  apps/webapp/src/data/faqs/getStusdsFaqsFaqItems.ts
  apps/webapp/src/data/faqs/getUpgradeFaqItems.ts
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/app/hooks/useBatchTxNotification.tsx
  apps/webapp/src/modules/app/hooks/useNotification.tsx
  apps/webapp/src/modules/chat/components/ChatIntentsRow.tsx
  apps/webapp/src/modules/chat/components/ConfirmationWarningRow.tsx
  apps/webapp/src/modules/layout/components/ConnectCard.tsx
  apps/webapp/src/modules/stusds/components/StUSDSUtilizationCard.tsx
  apps/webapp/src/modules/ui/components/AboutCard.tsx
  apps/webapp/src/modules/ui/components/AboutStUsds.tsx
  apps/webapp/src/modules/ui/components/GradientShapeCard.tsx
  apps/webapp/src/modules/ui/components/markdown/ChatMarkdownRenderer.tsx
  apps/webapp/src/test/e2e/tests/expert-stusds.spec.ts
  packages/hooks/src/stusds/useStUsdsCapacityData.ts
  packages/widgets/src/data/tooltips/index.ts
  packages/widgets/src/shared/components/ui/UtilizationBar.tsx
  packages/widgets/src/shared/components/ui/card/InteractiveStatsCardWithAccordion.tsx
  packages/widgets/src/widgets/BalancesWidget/components/SavingsBalanceCard.tsx
  packages/widgets/src/widgets/BalancesWidget/components/StUSDSBalanceCard.tsx
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSStatsCard.tsx
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSSupplyWithdraw.tsx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: ready for review
