Repository jetstreamgg/tarmac, pull requests merged in 2025-08, with the labels that each got.

#633 Advanced widget with stUSDS module
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/lib/enums.ts
  apps/webapp/src/modules/advanced/components/AdvancedDetailsPane.tsx
  apps/webapp/src/modules/advanced/components/AdvancedRiskCheckbox.tsx
  apps/webapp/src/modules/advanced/components/AdvancedWidgetPane.tsx
  apps/webapp/src/modules/advanced/components/StusdsStatsCard.tsx
  apps/webapp/src/modules/app/components/DetailsPane.tsx
  apps/webapp/src/modules/app/components/MainApp.tsx
  apps/webapp/src/modules/app/components/SealMigrationApp.tsx
  apps/webapp/src/modules/app/components/WidgetNavigation.tsx
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/config/context/ConfigContext.tsx
  apps/webapp/src/modules/config/types/user-config.ts
  apps/webapp/src/modules/layout/components/ConnectCard.tsx
  apps/webapp/src/modules/layout/components/Typography.tsx
  apps/webapp/src/modules/stusds/components/StUSDSDetails.tsx
  apps/webapp/src/modules/stusds/components/StUSDSWidgetPane.tsx
  apps/webapp/src/modules/utils/deleteSearchParams.ts
  apps/webapp/src/modules/utils/validateSearchParams.ts
  apps/webapp/src/public/tokens/ethereum/stusds.svg
  apps/webapp/src/public/tokens/stusds.svg
  packages/widgets/src/index.ts
  packages/widgets/src/shared/components/icons/Info.tsx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: ready for review

#644 Add hover state to reward cards in Rewards and Stake widgets
  packages/widgets/src/widgets/RewardsWidget/components/RewardsStatsCard.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/SaRewardsCard.tsx
Labels: ready for review

#637 add search functionality to trade token input
  packages/widgets/src/shared/components/ui/token/TokenInput.tsx
  packages/widgets/src/widgets/TradeWidget/components/TradeInputs.tsx
  packages/widgets/src/widgets/TradeWidget/index.tsx
Labels: ready for review

#647 Stusds clear input after successful tx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: ready for review

#649 Add support for base account
  apps/webapp/package.json
  apps/webapp/src/data/wagmi/config/baseAccount.svg
  apps/webapp/src/data/wagmi/config/baseAccount.ts
  apps/webapp/src/data/wagmi/config/config.default.ts
  apps/webapp/vite.config.ts
  packages/hooks/package.json
  packages/utils/package.json
  packages/widgets/package.json
  pnpm-lock.yaml
Labels: ready for review

#651 Add a max capacity stat card, remaining capacity card and dummy suppliers card
  apps/webapp/src/modules/stusds/components/StUSDSCapCard.tsx
  apps/webapp/src/modules/stusds/components/StUSDSInfoDetails.tsx
  apps/webapp/src/modules/stusds/components/StUSDSRemainingCapacityCard.tsx
  apps/webapp/src/modules/stusds/components/StUSDSSuppliersCard.tsx
Labels: RFC

#656 update variable names
  packages/hooks/src/stusds/stusds.d.ts
  packages/hooks/src/stusds/useStUsdsRateData.ts
Labels: ready for review

#657 Expert module overview details
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/lib/utils.ts
  apps/webapp/src/modules/advanced/helpers/expertModules.ts
  apps/webapp/src/modules/app/components/MainApp.tsx
  apps/webapp/src/modules/config/context/ConfigContext.tsx
  apps/webapp/src/modules/expert/components/ExpertAbout.tsx
  apps/webapp/src/modules/expert/components/ExpertChart.tsx
  apps/webapp/src/modules/expert/components/ExpertDetailsPane.tsx
  apps/webapp/src/modules/expert/components/ExpertOverview.tsx
  apps/webapp/src/modules/expert/components/ExpertSuppliersCard.tsx
  apps/webapp/src/modules/expert/components/ExpertTvlCard.tsx
  apps/webapp/src/modules/trade/components/TradeWidgetPane.tsx
  apps/webapp/src/modules/ui/components/AboutStUsds.tsx
  apps/webapp/src/modules/ui/components/HighlightRate.tsx
  apps/webapp/src/modules/ui/components/LinkedActionCard.tsx
  apps/webapp/src/modules/ui/components/LinkedActionWrapper.tsx
  apps/webapp/src/modules/ui/hooks/useUserSuggestedActions.ts
  apps/webapp/src/modules/upgrade/components/UpgradeWidgetPane.tsx
  apps/webapp/src/modules/utils/deleteSearchParams.ts
  apps/webapp/src/modules/utils/validateSearchParams.ts
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: ready for review

#662 Remove Savings restrictions for Mica
  apps/webapp/src/modules/savings/components/SavingsWidgetPane.tsx
Labels: ready for review

#665 Fetch reward token symbol for balances widget history
  packages/widgets/src/widgets/BalancesWidget/components/BalancesHistory.tsx
  packages/widgets/src/widgets/BalancesWidget/components/BalancesHistoryItem.tsx
  packages/widgets/src/widgets/BalancesWidget/lib/getHistoryRightText.ts
  packages/widgets/src/widgets/BalancesWidget/lib/getPositive.ts
  packages/widgets/src/widgets/BalancesWidget/lib/getToken.ts
Labels: ready for review

#666 Staging -> Main
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/savings/components/SavingsBalanceDetails.tsx
  apps/webapp/src/modules/savings/components/SavingsWidgetPane.tsx
  apps/webapp/src/modules/utils/validateSearchParams.ts
  packages/widgets/src/widgets/BalancesWidget/components/BalancesHistory.tsx
  packages/widgets/src/widgets/BalancesWidget/components/BalancesHistoryItem.tsx
  packages/widgets/src/widgets/BalancesWidget/lib/getHistoryRightText.ts
  packages/widgets/src/widgets/BalancesWidget/lib/getPositive.ts
  packages/widgets/src/widgets/BalancesWidget/lib/getToken.ts
Labels: ready for review, release PR

#668 Revert bundled MKR upgrade limitation
  packages/utils/src/hooks/useIsMetaMaskWallet.ts
  packages/utils/src/index.ts
  packages/widgets/src/shared/components/ui/transaction/TransactionReview.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeTransactionReview.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#669 show susds balance in mainnet savings widget and details pane
  apps/webapp/src/modules/savings/components/SavingsBalanceDetails.tsx
  apps/webapp/src/test/e2e/tests/mainnet-savings.spec.ts
  packages/widgets/src/widgets/SavingsWidget/components/SavingsStatsCard.tsx
  packages/widgets/src/widgets/SavingsWidget/components/SupplyWithdraw.tsx
Labels: ready for review

#674 Filter suggested and linked actions that aren't supported by the chain
  apps/webapp/src/modules/ui/hooks/useUserSuggestedActions.ts
Labels: ready for review

#678 Preprod -> main. Add coinbase wallet connector back
  apps/webapp/src/data/wagmi/config/config.default.ts
Labels: ready for review

#679 Add SealDetailsPane to DetailsPane component
  apps/webapp/src/modules/app/components/DetailsPane.tsx
  packages/widgets/src/widgets/TradeWidget/components/TradeConfigMenu.tsx
  packages/widgets/src/widgets/TradeWidget/components/TradeHeader.tsx
Labels: ready for review

#660 stusds widget update - focus on the most important data
  packages/hooks/src/stusds/useStUsdsData.ts
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSStatsCard.tsx
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSStatsCardCore.tsx
  packages/widgets/src/widgets/StUSDSWidget/components/StUSDSSupplyWithdraw.tsx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
  packages/widgets/src/widgets/StUSDSWidget/tests/stUSDSWidget.test.tsx
Labels: ready for review, RFC

#681 Prevent widget changes when in a linked action
  apps/webapp/src/modules/trade/components/TradeWidgetPane.tsx
  apps/webapp/src/modules/upgrade/components/UpgradeWidgetPane.tsx
  packages/widgets/src/shared/types/widgetState.d.ts
  packages/widgets/src/widgets/L2TradeWidget/components/L2TradeInputs.tsx
  packages/widgets/src/widgets/L2TradeWidget/index.tsx
  packages/widgets/src/widgets/TradeWidget/components/TradeInputs.tsx
  packages/widgets/src/widgets/TradeWidget/index.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeRevert.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#659 Refactor: Stake rewards claiming dropdown
  packages/hooks/src/index.ts
  packages/hooks/src/rewards/useRewardContractsToClaim.ts
  packages/widgets/src/widgets/StakeModuleWidget/components/ClaimRewardsButton.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/ClaimRewardsDropdown.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/PositionDetail.tsx
Labels: ready for review

#693 Gp/banner updates
  apps/webapp/scripts/sync-content.sh
  apps/webapp/src/data/banners/banners.ts
  apps/webapp/src/data/faqs/getUpgradeFaqItems.ts
  apps/webapp/src/modules/layout/components/ConnectCard.tsx
  apps/webapp/src/utils/bannerContentParser.tsx
  packages/widgets/src/data/tooltips/index.ts
  packages/widgets/src/index.ts
  packages/widgets/src/shared/components/ui/PopoverRateInfo.tsx
Labels: ready for review, Feat: content management

#703 Add support for custom terms markdown file
  apps/webapp/.env.example
  apps/webapp/README.md
  apps/webapp/src/modules/ui/components/TermsModal.tsx
  apps/webapp/src/modules/ui/components/terms-loader.ts
Labels: ready for review

#708 Apply changes from widget refactor #1 PR to the stUSDS widget
  apps/webapp/src/modules/app/components/DetailsPane.tsx
  packages/widgets/src/shared/components/ui/PopoverRateInfo.tsx
  packages/widgets/src/widgets/StUSDSWidget/hooks/useStUsdsTransactionCallbacks.tsx
  packages/widgets/src/widgets/StUSDSWidget/hooks/useStUsdsTransactions.tsx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: ready for review

#700 Use flex wrap for the staking, rewards & savings details cards
  apps/webapp/src/modules/rewards/components/RewardsBalanceDetails.tsx
  apps/webapp/src/modules/rewards/components/RewardsTokenInfo.tsx
  apps/webapp/src/modules/savings/components/SavingsInfoDetails.tsx
  apps/webapp/src/modules/stake/components/StakeOverview.tsx
  apps/webapp/src/modules/stake/components/StakeRewardsOverview.tsx
Labels: ready for review

#701 Account for MKR -> SKY fee for Delayed Upgrade Penalty
  apps/webapp/src/modules/seal/components/SealPositionOverview.tsx
  apps/webapp/src/modules/upgrade/components/UpgradedMkrToSky.tsx
  packages/hooks/src/index.ts
  packages/hooks/src/upgrade/upgrade.d.ts
  packages/hooks/src/upgrade/useMkrSkyFee.ts
  packages/hooks/src/upgrade/useUpgradeTotals.ts
  packages/utils/src/math.ts
  packages/widgets/src/widgets/SealModuleWidget/components/Borrow.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Free.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/PositionDetail.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/PositionDetailsAccordion.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/PositionSummary.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Repay.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeRevert.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeStats.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#560 [Transaction flows refactor]: Unified transaction flow hooks
  .changeset/three-wolves-grab.md
  packages/hooks/src/hooks.d.ts
  packages/hooks/src/index.ts
  packages/hooks/src/psm/useBatchPsmSwapExactIn.ts
  packages/hooks/src/psm/useBatchPsmSwapExactOut.ts
  packages/hooks/src/rewards/useBatchRewardsSupply.ts
  packages/hooks/src/savings/useBatchSavingsSupply.ts
  packages/hooks/src/shared/useSequentialTransactionFlow.tsx
  packages/hooks/src/shared/useTransactionFlow.ts
  packages/hooks/src/stake/useBatchStakeMulticall.ts
  packages/widgets/src/widgets/L2SavingsWidget/hooks/useL2SavingsTransactionCallbacks.tsx
  packages/widgets/src/widgets/L2SavingsWidget/hooks/useL2SavingsTransactions.tsx
  packages/widgets/src/widgets/L2SavingsWidget/index.tsx
  packages/widgets/src/widgets/L2TradeWidget/components/L2TradeTransactionStatus.tsx
  packages/widgets/src/widgets/L2TradeWidget/hooks/useL2TradeTransactionCallbacks.tsx
  packages/widgets/src/widgets/L2TradeWidget/hooks/useL2TradeTransactions.tsx
  packages/widgets/src/widgets/L2TradeWidget/index.tsx
  packages/widgets/src/widgets/RewardsWidget/components/RewardsTransactionStatus.tsx
  packages/widgets/src/widgets/RewardsWidget/hooks/useRewardsTransactionCallbacks.tsx
  packages/widgets/src/widgets/RewardsWidget/hooks/useRewardsTransactions.tsx
  packages/widgets/src/widgets/RewardsWidget/index.tsx
  packages/widgets/src/widgets/SavingsWidget/components/SavingsTransactionStatus.tsx
  packages/widgets/src/widgets/SavingsWidget/hooks/useSavingsTransactionCallbacks.tsx
  packages/widgets/src/widgets/SavingsWidget/hooks/useSavingsTransactions.tsx
  packages/widgets/src/widgets/SavingsWidget/index.tsx
  packages/widgets/src/widgets/StakeModuleWidget/components/StakeModuleTransactionStatus.tsx
  packages/widgets/src/widgets/StakeModuleWidget/hooks/useStakeTransactionCallbacks.tsx
  packages/widgets/src/widgets/StakeModuleWidget/hooks/useStakeTransactions.tsx
  packages/widgets/src/widgets/StakeModuleWidget/index.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeTransactionStatus.tsx
  packages/widgets/src/widgets/UpgradeWidget/hooks/useBatchUpgraderManager.tsx
  packages/widgets/src/widgets/UpgradeWidget/hooks/useUpgradeTransactionCallbacks.tsx
  packages/widgets/src/widgets/UpgradeWidget/hooks/useUpgradeTransactions.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review, feature

#709 Implement changes from widget refactor PRs #2 and #3 in stUSDS widget
  packages/hooks/src/stusds/useBatchStUsdsDeposit.ts
  packages/hooks/src/stusds/useStUsdsApprove.ts
  packages/hooks/src/stusds/useStUsdsDeposit.ts
  packages/hooks/src/stusds/useStUsdsWithdraw.ts
  packages/widgets/src/widgets/StUSDSWidget/hooks/useStUsdsTransactionCallbacks.tsx
  packages/widgets/src/widgets/StUSDSWidget/hooks/useStUsdsTransactions.tsx
  packages/widgets/src/widgets/StUSDSWidget/index.tsx
Labels: ready for review

#716 Unify terms loading with support for app and chatbot terms via terms-loader
  apps/webapp/.env.example
  apps/webapp/README.md
  apps/webapp/src/modules/chat/components/ChatWithTerms.tsx
  apps/webapp/src/modules/ui/components/terms-loader.ts
Labels: ready for review

#721 Use new upgrade datapoints in widget
  apps/webapp/src/modules/upgrade/components/MkrUpgradedToSky.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeStats.tsx
Labels: ready for review

#722 Staging - > development
  apps/webapp/src/modules/balances/components/BalancesSkyStatsOverview.tsx
  apps/webapp/src/modules/upgrade/components/MkrUpgradedPercentage.tsx
  apps/webapp/src/modules/upgrade/components/MkrUpgradedToSky.tsx
  apps/webapp/src/modules/upgrade/components/UpgradeStats.tsx
  apps/webapp/src/modules/upgrade/components/UpgradedDaiToUsds.tsx
  apps/webapp/src/modules/upgrade/components/UpgradedMkrToSky.tsx
  apps/webapp/src/test/e2e/tests/upgrade.spec.ts
  packages/hooks/src/index.ts
  packages/hooks/src/upgrade/useMigrationStats.ts
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeStats.tsx
Labels: ready for review

#724 Add publishConfig for public access in package.json files
  packages/hooks/package.json
  packages/utils/package.json
  packages/widgets/package.json
Labels: ready for review

#717 Chatbot first suggested questions
  apps/webapp/.env.example
  apps/webapp/README.md
  apps/webapp/src/modules/app/components/ChatPane.tsx
  apps/webapp/src/modules/chat/components/ChatBubble.tsx
  apps/webapp/src/modules/chat/components/ChatIntentsRow.tsx
Labels: ready for review
