Repository jetstreamgg/tarmac, pull requests merged in 2025-02, with the labels that each got.

#46 Fix source and target tokens in url for sUSDS in the Trade widgets
  .changeset/flat-tables-relax.md
  packages/widgets/src/lib/utils.ts
  packages/widgets/src/widgets/BaseTradeWidget/index.tsx
  packages/widgets/src/widgets/TradeWidget/index.tsx
  packages/widgets/src/widgets/TradeWidget/lib/constants.ts
Labels: ready for review

#47 Update Typescript's `moduleResolution` to `bundler`
  apps/integration-ui/tsconfig.node.json
  apps/webapp/tsconfig.node.json
  packages/hooks/src/index.ts
  packages/hooks/src/rewards/useRewardsSupply.tsx
  packages/widgets/src/widgets/RewardsWidget/components/RewardsStatsCardCore.tsx
  packages/widgets/src/widgets/RewardsWidget/index.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Borrow.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/DelegateCard.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/UrnPosition.tsx
  tsconfig.json
Labels: ready for review

#44 Fix alignment issue in Trade Widget
  apps/webapp/src/components/DualSwitcher.tsx
Labels: ready for review

#38 Generate trade intents for the chatbot
  apps/webapp/src/modules/chat/components/ChatConfirmationModal.tsx
  apps/webapp/src/modules/chat/components/ChatIntentsRow.tsx
  apps/webapp/src/modules/chat/hooks/__mocks__/mock-chat-endpoints.ts
  apps/webapp/src/modules/chat/hooks/useSendMessage.tsx
  apps/webapp/src/modules/chat/lib/generateTradeIntents.ts
  apps/webapp/src/modules/chat/lib/handleActionIntent.ts
  apps/webapp/src/modules/chat/lib/intentClassificationOptions.ts
  packages/widgets/src/lib/utils.ts
  packages/widgets/src/widgets/TradeWidget/index.tsx
  packages/widgets/src/widgets/TradeWidget/lib/constants.ts
Labels: ready for review

#51 fix issue with dialog and pasing empty string to img src
  apps/webapp/src/modules/layout/components/UnsupportedNetworkPage.tsx
  packages/widgets/src/widgets/BalancesWidget/components/AssetBalance.tsx
Labels: ready for review

#56 Update missing dependencies
  apps/integration-ui/package.json
  apps/webapp/package.json
  apps/webapp/tailwind.config.ts
  packages/widgets/package.json
  pnpm-lock.yaml
Labels: ready for review

#59 Make specific reference to wdigets package in tailwind config
  apps/integration-ui/src/pages/App.tsx
  apps/integration-ui/tailwind.config.js
  apps/webapp/src/pages/main.tsx
  apps/webapp/tailwind.config.ts
  packages/widgets/package.json
  packages/widgets/tailwind.config.js
Labels: ready for review

#58 Update syntax: JSON type assertion from `assert` to `with`
  apps/webapp/src/data/wagmi/config/testTenderlyChain.ts
Labels: ready for review

#53 Remove npm-run-all, cross-spawn@6.0.5
  package.json
  pnpm-lock.yaml
Labels: ready for review

#54 Update lint-staged, remove micromatch 4.0.5
  package.json
  pnpm-lock.yaml
Labels: ready for review

#57 Arbitrum USDS and sUSDS contracts
  packages/hooks/src/contracts.ts
Labels: ready for review

#55 Generate chatbot save intents
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/modules/app/components/MainApp.tsx
  apps/webapp/src/modules/chat/components/ChatConfirmationModal.tsx
  apps/webapp/src/modules/chat/hooks/__mocks__/mock-chat-endpoints.ts
  apps/webapp/src/modules/chat/hooks/useSendMessage.tsx
  apps/webapp/src/modules/chat/lib/generateRewardIntents.ts
  apps/webapp/src/modules/chat/lib/generateSavingsIntents.ts
  apps/webapp/src/modules/chat/lib/generateTradeIntents.ts
  apps/webapp/src/modules/chat/lib/generateUpgradeIntents.ts
  apps/webapp/src/modules/chat/lib/handleActionIntent.ts
  apps/webapp/src/modules/chat/lib/intentUtils.ts
  apps/webapp/src/modules/chat/types/Chat.ts
  apps/webapp/src/modules/savings/components/SavingsWidgetPane.tsx
  apps/webapp/src/modules/utils/validateSearchParams.ts
  packages/widgets/src/shared/types/widgetState.d.ts
  packages/widgets/src/widgets/BaseSavingsWidget/components/BaseSavingsSupplyWithdraw.tsx
  packages/widgets/src/widgets/BaseSavingsWidget/index.tsx
  packages/widgets/src/widgets/SavingsWidget/components/SupplyWithdraw.tsx
  packages/widgets/src/widgets/SavingsWidget/index.tsx
Labels: ready for review

#61 add tooltip for delegate
  packages/widgets/src/widgets/SealModuleWidget/components/About.tsx
Labels: ready for review

#60 Add Coderabbit config file
  .coderabbit.yaml
Labels: ready for review

#62 Apply fixture to Arbitrum and L2 test files
  apps/webapp/src/test/e2e/fixtures.ts
  apps/webapp/src/test/e2e/tests/arbitrum-savings.spec.ts
  apps/webapp/src/test/e2e/tests/arbitrum-trade.spec.ts
  apps/webapp/src/test/e2e/tests/base-savings.spec.ts
  apps/webapp/src/test/e2e/tests/base-trade.spec.ts
  apps/webapp/src/test/e2e/tests/l2-savings.ts
  apps/webapp/src/test/e2e/tests/l2-trade.ts
  packages/hooks/test/WagmiWrapper.tsx
  packages/hooks/test/globalSetup.ts
  packages/hooks/test/setup.ts
Labels: ready for review

#68 Update etherscan v2 api key
  packages/hooks/.env.example
  packages/hooks/README.md
  packages/hooks/src/contracts.ts
  packages/hooks/src/generated.ts
  packages/hooks/wagmi.config.ts
Labels: ready for review

#65 Fix dependabot alert 5 by updating and removing packages
  .changeset/chilly-pumpkins-perform.md
  .eslintignore
  .eslintrc.json
  apps/integration-ui/package.json
  apps/integration-ui/src/i18n.ts
  apps/integration-ui/src/modules/landing/components/ActionButtons.tsx
  apps/webapp/package.json
  apps/webapp/src/components/ui/use-toast.ts
  apps/webapp/src/i18n.ts
  apps/webapp/src/lib/utils.ts
  apps/webapp/src/modules/auth/components/UnauthorizedPage.tsx
  apps/webapp/src/modules/layout/components/ExternalLinkModal.tsx
  apps/webapp/src/modules/seal/components/SealWidgetPane.tsx
  apps/webapp/src/modules/ui/components/ChainModal.tsx
  apps/webapp/src/test/e2e/utils/connectMockWalletAndAcceptTerms.ts
  eslint.config.mjs
  package.json
  packages/hooks/src/dsProxy/useDsProxyBuild.ts
  packages/hooks/src/shared/useWriteContractFlow.tsx
  packages/hooks/src/trade/useSignAndCancelOrder.ts
  packages/hooks/src/trade/useSignAndCreateTradeOrder.tsx
  packages/utils/src/formatDate.ts
  packages/widgets/src/context/I18nWidgetProvider.tsx
  packages/widgets/src/shared/components/ui/token/TokenInput.tsx
  packages/widgets/src/widgets/BalancesWidget/index.tsx
  packages/widgets/src/widgets/BaseSavingsWidget/index.tsx
  packages/widgets/src/widgets/BaseTradeWidget/index.tsx
  packages/widgets/src/widgets/RewardsWidget/index.tsx
  packages/widgets/src/widgets/SavingsWidget/index.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Free.tsx
  packages/widgets/src/widgets/TradeWidget/index.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
  pnpm-lock.yaml
Labels: dependencies, ready for review

#66 Add Safe App toast for WalletConnect connections
  apps/webapp/src/locales/en.po
  apps/webapp/src/locales/en.ts
  apps/webapp/src/locales/es-AR.po
  apps/webapp/src/locales/es-AR.ts
  apps/webapp/src/locales/es-ES.po
  apps/webapp/src/locales/es-ES.ts
  apps/webapp/src/locales/es.po
  apps/webapp/src/locales/es.ts
  apps/webapp/src/locales/ko.po
  apps/webapp/src/locales/ko.ts
  apps/webapp/src/modules/app/components/MainApp.tsx
  apps/webapp/src/modules/app/hooks/useSafeAppNotification.tsx
  apps/webapp/src/modules/config/context/ConfigContext.tsx
  packages/utils/src/hooks/useIsSafeWallet.ts
  packages/utils/src/hooks/useIsSmartContractWallet.ts
  packages/utils/src/index.ts
Labels: ready for review

#71 Update widget docs
  packages/widgets/README.md
Labels: ready for review

#67 Add new Tenderly Arbitrum forked chain with PSM3 contracts funded
  apps/integration-ui/src/modules/providers/wagmi.ts
  apps/webapp/src/data/wagmi/config/config.default.ts
  apps/webapp/src/data/wagmi/config/testTenderlyChain.ts
  apps/webapp/vite.config.ts
  packages/hooks/.env.example
  packages/hooks/README.md
  packages/hooks/src/contracts.ts
  packages/hooks/src/generated.ts
  packages/hooks/src/tokens/tokens.constants.ts
  packages/hooks/wagmi.config.ts
  packages/utils/src/getEtherscanLink.ts
  scripts/forkVnet.ts
Labels: ready for review

#80 dev > staging
  .changeset/chilly-dancers-end.md
  apps/integration-ui/package.json
  apps/webapp/package.json
  apps/webapp/src/locales/en.po
  apps/webapp/src/locales/en.ts
  apps/webapp/src/locales/es-AR.po
  apps/webapp/src/locales/es-AR.ts
  apps/webapp/src/locales/es-ES.po
  apps/webapp/src/locales/es-ES.ts
  apps/webapp/src/locales/es.po
  apps/webapp/src/locales/es.ts
  apps/webapp/src/locales/ko.po
  apps/webapp/src/locales/ko.ts
  apps/webapp/src/modules/app/hooks/useSafeAppNotification.tsx
  packages/hooks/package.json
  packages/utils/package.json
  packages/widgets/package.json
  pnpm-lock.yaml
Labels: ready for review

#82 Add associated network icons in chat intent buttons
  apps/webapp/src/modules/chat/components/ChatIntentsRow.tsx
  apps/webapp/src/modules/chat/hooks/__mocks__/mock-chat-endpoints.ts
  apps/webapp/src/modules/chat/hooks/useNetworkFromUrl.tsx
  apps/webapp/src/modules/chat/lib/intentUtils.ts
  apps/webapp/src/public/networks/arbitrum.svg
  apps/webapp/src/public/networks/base.svg
  apps/webapp/src/public/networks/ethereum.svg
Labels: ready for review

#83 staging > main
  .changeset/chilly-dancers-end.md
  apps/integration-ui/package.json
  apps/webapp/package.json
  apps/webapp/src/locales/en.po
  apps/webapp/src/locales/en.ts
  apps/webapp/src/locales/es-AR.po
  apps/webapp/src/locales/es-AR.ts
  apps/webapp/src/locales/es-ES.po
  apps/webapp/src/locales/es-ES.ts
  apps/webapp/src/locales/es.po
  apps/webapp/src/locales/es.ts
  apps/webapp/src/locales/ko.po
  apps/webapp/src/locales/ko.ts
  apps/webapp/src/modules/app/hooks/useSafeAppNotification.tsx
  packages/hooks/package.json
  packages/utils/package.json
  packages/widgets/package.json
  pnpm-lock.yaml
Labels: ready for review

#86 Make the mainnet Savings widget react to changes in the external state
  apps/webapp/src/modules/chat/components/ChatIntentsRow.tsx
  apps/webapp/src/modules/savings/components/SavingsWidgetPane.tsx
  packages/widgets/src/widgets/L2SavingsWidget/components/L2SavingsSupplyWithdraw.tsx
  packages/widgets/src/widgets/L2SavingsWidget/index.tsx
  packages/widgets/src/widgets/SavingsWidget/components/SupplyWithdraw.tsx
  packages/widgets/src/widgets/SavingsWidget/index.tsx
Labels: ready for review

#91 Normalize network names in the search params
  apps/webapp/src/lib/helpers/string/normalizeUrlParam.ts
  apps/webapp/src/modules/app/components/MainApp.tsx
  apps/webapp/src/modules/chat/hooks/__mocks__/mock-chat-endpoints.ts
  apps/webapp/src/modules/chat/hooks/useNetworkFromUrl.tsx
  apps/webapp/src/modules/chat/hooks/useSendMessage.tsx
  apps/webapp/src/modules/chat/lib/intentUtils.ts
  apps/webapp/src/modules/layout/components/UnsupportedNetworkPage.tsx
  apps/webapp/src/modules/ui/components/ChainModal.tsx
  apps/webapp/src/modules/utils/validateSearchParams.ts
  apps/webapp/src/public/networks/arbitrumone.svg
  apps/webapp/src/test/e2e/tests/landing.spec.ts
Labels: ready for review

#93 disable arbitrum on prod
  apps/webapp/src/data/wagmi/config/config.default.ts
  apps/webapp/src/modules/ui/components/TermsModal.tsx
Labels: ready for review

#95 Rename Tab search params actions to Flow
  apps/integration-ui/src/modules/landing/Landing.tsx
  apps/integration-ui/src/modules/landing/LandingArbitrum.tsx
  apps/integration-ui/src/modules/landing/LandingBase.tsx
  apps/integration-ui/src/modules/landing/LandingSepolia.tsx
  apps/integration-ui/src/modules/landing/widgets/BalancesWidgetDisplay.tsx
  apps/integration-ui/src/modules/landing/widgets/TradeWidgetDisplay.tsx
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/modules/app/components/WidgetPane.tsx
  apps/webapp/src/modules/balances/components/BalancesWidgetPane.tsx
  apps/webapp/src/modules/savings/components/SavingsWidgetPane.tsx
  apps/webapp/src/modules/upgrade/components/UpgradeWidgetPane.tsx
  packages/widgets/src/index.ts
  packages/widgets/src/lib/utils.ts
  packages/widgets/src/shared/types/widgetState.d.ts
  packages/widgets/src/widgets/BalancesWidget/components/BalancesContent.tsx
  packages/widgets/src/widgets/BalancesWidget/components/BalancesHeader.tsx
  packages/widgets/src/widgets/BalancesWidget/components/BalancesTabsList.tsx
  packages/widgets/src/widgets/BalancesWidget/constants.ts
  packages/widgets/src/widgets/BalancesWidget/index.tsx
  packages/widgets/src/widgets/L2SavingsWidget/index.tsx
  packages/widgets/src/widgets/RewardsWidget/components/ManagePosition.tsx
  packages/widgets/src/widgets/RewardsWidget/index.tsx
  packages/widgets/src/widgets/SavingsWidget/index.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeRevert.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#96 Listen for changes in the search parameters and update the state accordingly
  apps/webapp/src/modules/balances/components/BalancesWidgetPane.tsx
  apps/webapp/src/modules/rewards/components/RewardsWidgetPane.tsx
  apps/webapp/src/modules/savings/components/SavingsWidgetPane.tsx
  apps/webapp/src/modules/upgrade/components/UpgradeWidgetPane.tsx
  apps/webapp/src/modules/utils/validateSearchParams.ts
  packages/widgets/src/widgets/L2SavingsWidget/index.tsx
  packages/widgets/src/widgets/RewardsWidget/components/ManagePosition.tsx
  packages/widgets/src/widgets/RewardsWidget/index.tsx
Labels: ready for review

#101 Convert cursor rules to rules dir
  .cursor/rules/cursor-rules.mdc
  .cursor/rules/performance-optimization.mdc
  .cursor/rules/react-typescript-standards.mdc
  .cursor/rules/testing-standards.mdc
  .cursor/rules/ui-styling.mdc
  .cursor/rules/web3-integration.mdc
  .cursorrules
Labels: ready for review

#104 main > development
  apps/webapp/package.json
  apps/webapp/src/data/wagmi/config/config.default.ts
  apps/webapp/vite.config.ts
  pnpm-lock.yaml
Labels: ready for review

#102 Fix rewards overview TVL chart
  .changeset/bright-beds-crash.md
  apps/webapp/src/modules/rewards/components/history/RewardsOverviewCharts.tsx
Labels: ready for review

#110 Rename chatbot
  apps/webapp/.env.example
  apps/webapp/README.md
  apps/webapp/src/modules/chat/constants.ts
Labels: ready for review

#107 Handle seal query params
  apps/webapp/src/lib/constants.ts
  apps/webapp/src/modules/seal/components/SealWidgetPane.tsx
  packages/widgets/src/lib/utils.ts
  packages/widgets/src/shared/types/widgetState.d.ts
  packages/widgets/src/widgets/SealModuleWidget/components/Free.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Lock.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/OpenNewUrn.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/UnconnectedState.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
Labels: ready for review, do not merge

#108 Patch esbuild
  package.json
  pnpm-lock.yaml
Labels: ready for review

#105 main > staging
  apps/webapp/src/modules/rewards/components/history/RewardsOverviewCharts.tsx
  pnpm-lock.yaml
Labels: ready for review

#112 Make widget tooltips scrollable
  .changeset/flat-ducks-yell.md
  packages/widgets/src/shared/components/ui/tooltip/InfoTooltip.tsx
Labels: ready for review

#116 Fixes for QA findings
  apps/webapp/src/globals.css
  apps/webapp/src/modules/auth/components/UnauthorizedPage.tsx
  apps/webapp/src/modules/layout/components/ExternalLinkModal.tsx
  apps/webapp/src/modules/rewards/components/RewardsDetailsView.tsx
  apps/webapp/src/modules/rewards/components/RewardsTokenInfo.tsx
  apps/webapp/src/modules/ui/components/ChainModal.tsx
  apps/webapp/src/modules/ui/components/CopyToClipboard.tsx
  apps/webapp/src/modules/ui/components/TermsModal.tsx
  packages/hooks/src/tokens/tokens.constants.ts
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/components/ui/card.tsx
  packages/widgets/src/globals.css
  packages/widgets/src/shared/components/ExternalLink.tsx
  packages/widgets/src/shared/components/ui/token/TokenInput.tsx
  packages/widgets/src/shared/constants.ts
  packages/widgets/src/widgets/BalancesWidget/components/AssetBalance.tsx
  packages/widgets/src/widgets/RewardsWidget/index.tsx
  packages/widgets/src/widgets/SavingsWidget/components/SavingsStatsCardCore.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/DelegateCard.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/SaRewardsCard.tsx
Labels: ready for review

#120 update some ts annotations
  packages/widgets/src/widgets/RewardsWidget/tests/rewardsWidget.test.tsx
  packages/widgets/src/widgets/SavingsWidget/tests/savingsWidget.test.tsx
  packages/widgets/src/widgets/TradeWidget/tests/tradeWidget.test.tsx
  packages/widgets/src/widgets/UpgradeWidget/tests/upgradeWidget.test.tsx
  scripts/deleteVnet.ts
  scripts/forkVnet.ts
Labels: ready for review

#123 Gp/staging main
  packages/widgets/src/widgets/SealModuleWidget/components/Borrow.tsx
Labels: ready for review

#119 Main -> staging
  packages/widgets/src/widgets/SealModuleWidget/components/Borrow.tsx
Labels: do not merge

#122 No Balances Found
  apps/webapp/src/modules/balances/components/BalancesAssets.tsx
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
  packages/widgets/src/shared/components/ui/card/InteractiveStatsCardWithAccordion.tsx
  packages/widgets/src/widgets/BalancesWidget/components/BalancesContent.tsx
  packages/widgets/src/widgets/BalancesWidget/components/ModulesBalances.tsx
  packages/widgets/src/widgets/BalancesWidget/components/RewardsBalanceCard.tsx
  packages/widgets/src/widgets/BalancesWidget/components/SavingsBalanceCard.tsx
  packages/widgets/src/widgets/BalancesWidget/components/SealBalanceCard.tsx
  packages/widgets/src/widgets/BalancesWidget/components/TokenBalances.tsx
Labels: ready for review

#129 Add network toast, remove network switcher from ModuleCards
  apps/webapp/src/modules/app/hooks/useNetworkChangeNotification.tsx
  apps/webapp/src/modules/balances/components/ModuleCard.tsx
  apps/webapp/src/modules/layout/components/Layout.tsx
Labels: ready for review

#130 Update colors of the RainbowKit modal
  apps/webapp/src/themes/rainbowTheme.ts
Labels: ready for review

#132 Fix opacity in StepIndicator
  packages/widgets/src/shared/components/ui/transaction/StepIndicator.tsx
Labels: ready for review

#134 Arbitrum and Base banners
  .changeset/perfect-seas-dance.md
  apps/webapp/src/modules/layout/components/ConnectCard.tsx
  packages/utils/src/locales/en.po
  packages/utils/src/locales/en.ts
  packages/utils/src/locales/es-AR.po
  packages/utils/src/locales/es-AR.ts
  packages/utils/src/locales/es-ES.po
  packages/utils/src/locales/es-ES.ts
  packages/utils/src/locales/es.po
  packages/utils/src/locales/es.ts
  packages/utils/src/locales/ko.po
  packages/utils/src/locales/ko.ts
Labels: ready for review

#135 Fix navigation tab sizes on mobile layout
  .changeset/poor-bobcats-punch.md
  apps/webapp/src/modules/app/components/WidgetNavigation.tsx
Labels: ready for review

#137 match the no history found to the no balances found design
  packages/widgets/src/widgets/BalancesWidget/components/BalancesHistory.tsx
Labels: ready for review

#138 Add Safe Arbitrum endpoints
  apps/webapp/vite.config.ts
  packages/hooks/src/shared/constants.ts
  packages/utils/src/hooks/useIsSafeWallet.ts
Labels: ready for review

#131 Seal fixes
  packages/utils/src/formatValue.ts
  packages/widgets/src/shared/components/ui/transaction/TransactionOverview.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/About.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Borrow.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/PositionSummary.tsx
  packages/widgets/src/widgets/SealModuleWidget/components/Repay.tsx
Labels: ready for review

#111 Add ConfirmationWarningRow which will replace the confirmation modal
  apps/webapp/src/modules/app/components/ChatPane.tsx
  apps/webapp/src/modules/chat/components/ChatConfirmationModal.tsx
  apps/webapp/src/modules/chat/components/ChatIntentsRow.tsx
  apps/webapp/src/modules/chat/components/ConfirmationWarningRow.tsx
  apps/webapp/src/modules/chat/constants.ts
  apps/webapp/src/modules/chat/context/ChatContext.tsx
  apps/webapp/src/modules/chat/lib/confirmationWarningMetadata.ts
  apps/webapp/src/modules/chat/lib/intentUtils.ts
  apps/webapp/src/modules/icons/Warning.tsx
  packages/widgets/src/widgets/SealModuleWidget/index.tsx
Labels: ready for review

#127 Handle Upgrade widget params
  apps/webapp/src/modules/upgrade/components/UpgradeWidgetPane.tsx
  apps/webapp/src/modules/utils/validateSearchParams.ts
  packages/widgets/src/lib/utils.ts
  packages/widgets/src/widgets/L2SavingsWidget/index.tsx
  packages/widgets/src/widgets/UpgradeWidget/components/UpgradeRevert.tsx
  packages/widgets/src/widgets/UpgradeWidget/index.tsx
Labels: ready for review

#140 Step indicator fix for l2 savings withdraw
  packages/widgets/src/widgets/L2SavingsWidget/index.tsx
Labels: ready for review
